### ISSUE TITLE
Missing from the checklist: SEO details in page header update with changes to the SEO component

### ISSUE THREAD

**Issue by prokopsimek** [xoksam/gridsome-starter-buttercms#9]
SEO is not loaded from the ButterCMS API.

<img width="770" alt="image" src="https://user-images.githubusercontent.com/5487217/202661136-a6d893c7-1798-4450-a79a-75231180ca3b.png">

<img width="576" alt="image" src="https://user-images.githubusercontent.com/5487217/202661207-76abcc2b-f19f-4e7a-a48c-36377eb78f57.png">

**Comment by xoksam** [comment]
Fixed using `gridsome-plugin-seo`
